# Generated by Django 3.1.2 on 2020-10-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Name',
            new_name='name',
        ),
    ]
