# Generated by Django 3.1.2 on 2020-10-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20201005_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Sname',
            new_name='name',
        ),
    ]
